function names = curveParamNames()
% curveParamNames  Ordered curve design parameter names (17 total).
%
%   anglePlusDeg / angleMinusDeg give the optimizer independent inclination
%   for each helix family.  bevelRingWeight / bevelRingWidthFactor reinforce
%   the inclined (alpha-angled) joint face where stress concentrations occur;
%   flatRingWeight / flatRingWidthFactor reinforce the perpendicular z=0 face.
%   Legacy jointRingWeight / jointRingWidthFactor are kept as fallbacks in
%   buildCurveLinkedDensity but are no longer optimization variables.

    names = {'phaseFrac', 'spacingFactor', 'widthFactor', ...
        'helixPlusWeight',  'anglePlusDeg', ...
        'helixMinusWeight', 'angleMinusDeg', ...
        'axialWeight', 'bendingWeight', ...
        'ringWeight', 'ringSpacingFactor', ...
        'bevelRingWeight', 'bevelRingWidthFactor', ...
        'flatRingWeight',  'flatRingWidthFactor', ...
        'middleRingWeight', ...
        'baseDensity'};
end
