function names = curveParamNames()
% curveParamNames  Ordered curve design parameter names.

    names = {'angleDeg', 'phaseFrac', 'spacingFactor', 'widthFactor', ...
        'helixPlusWeight', 'helixMinusWeight', ...
        'axialWeight', 'bendingWeight', ...
        'ringWeight', 'ringSpacingFactor', 'jointRingWeight', ...
        'baseDensity'};
end
