function names = curveParamNames()
% curveParamNames  Ordered curve design parameter names (13 total).
%
%   anglePlusDeg / angleMinusDeg replace the old shared angleDeg, giving the
%   optimizer independent inclination for each helix family.  The shared
%   angleDeg field is kept as a legacy fallback in buildCurveLinkedDensity.

    names = {'phaseFrac', 'spacingFactor', 'widthFactor', ...
        'helixPlusWeight',  'anglePlusDeg', ...
        'helixMinusWeight', 'angleMinusDeg', ...
        'axialWeight', 'bendingWeight', ...
        'ringWeight', 'ringSpacingFactor', ...
        'jointRingWeight', 'jointRingWidthFactor', ...
        'baseDensity'};
end
